const ALL_FAILED = "No provider could answer for this record.";

export const ENRICHMENT_STRINGS = {
  nav: "Enrichment",
  settings: {
    title: "Enrichment",
    description:
      "Connect a lead-research provider so Fill the gaps can complete a person or an organization. Enabling a provider sends the record's name, email, or domain to that provider.",
    providersTitle: "Providers",
    providersDescription: "Keys are stored encrypted and are never shown again after saving.",
    apiKeyLabel: "API key",
    apiKeyPlaceholder: "Paste the key",
    providerNames: {
      apollo: "Apollo",
      rocketreach: "RocketReach",
      getprospect: "GetProspect",
    },
    save: "Save key",
    saving: "Saving",
    remove: "Remove key",
    removeConfirm: "Remove",
    removeConfirmTitle: "Remove this API key?",
    removeConfirmBody:
      "The provider is switched off and stops answering Fill the gaps until a new key is saved.",
    test: "Test connection",
    testCost:
      "Testing makes one organization and one person lookup, so it spends a credit for each.",
    testOk: "Key works.",
    testNoMatch: "Key works. The probe found no data, which is fine.",
    testFailed: (verdict: string) => `Test failed: ${verdict}.`,
    testQuotaHourly: (left: number) => `${left} left this hour`,
    testQuotaDaily: (left: number) => `${left} left today`,
    testQuotaLine: (windows: string) => `Remaining calls: ${windows}.`,
    testLookupPerson: "person lookups",
    testLookupOrganization: "organization lookups",
    testLookupSeparator: " or ",
    testNotEntitledLine: (lookups: string) => `This plan does not include ${lookups}.`,
    testing: "Testing",
    enabledLabel: "Use this provider",
    needsKeyFirst: "Add an API key first",
    statusNoKey: "No key",
    statusEnabled: "Enabled",
    statusDisabled: "Disabled",
    statusRejected: "Key rejected",
    statusThrottled: (until: string) => `Rate limited until ${until}`,
    statusQuota: (until: string) => `Out of credits until ${until}`,
    keyHint: (hint: string) => `Key ending ${hint}`,
    mappingTitle: "Field mapping",
    mappingDescription:
      "Where each piece of provider data is written. Anything left unmapped is never written.",
    mappingPerson: "Person",
    mappingOrganization: "Organization",
    mappingColField: "Provider field",
    mappingColTarget: "Writes to",
    mappingNotMapped: "Not mapped",
    mappingBuiltinGroup: "Built-in fields",
    mappingCustomGroup: "Custom fields",
    mappingNoCustomFields: "No custom fields for this entity yet.",
    mappingManageFields: "Manage data fields",
    cacheTitle: "Caching",
    cacheDescription:
      "How long a result is reused before a click calls the providers again. Zero disables the cache.",
    cacheLabel: "Reuse results for (days)",
    cacheSave: "Save",
    cacheInvalid: "Enter a whole number of days, 0 to 365.",
    saveError: "Could not save. Try again.",
    adminOnly: "Only an admin can configure enrichment.",
  },
  dialog: {
    title: (name: string) => `Fill the gaps: ${name}`,
    loading: "Asking the connected providers",
    subtitle: "Pick what to write onto this record.",
    cached: (when: string) => `Enriched ${when}. Showing the saved result.`,
    refresh: "Refresh",
    apply: (count: number) => (count === 1 ? "Apply 1 field" : `Apply ${count} fields`),
    applying: "Applying",
    cancel: "Cancel",
    nothingFound: "Nothing new found.",
    overwrites: (current: string) => `Overwrites "${current}"`,
    overwritesHidden: "Overwrites a value you do not have access to",
    relinksOrganization: (current: string) =>
      `Links this person to another organization, replacing "${current}"`,
    currentInvalid: (current: string) => `"${current}" is not a valid address`,
    primaryChoiceLabel: "Where it goes",
    addAlongside: "Add alongside the current one",
    addAsPrimary: "Add and make it the primary",
    sources: "Sources",
    sourceCount: (count: number) => (count === 1 ? "1 source" : `${count} sources`),
    pickOne: "Providers disagree. Pick a value.",
    applyError: "Could not apply. Nothing was changed.",
    unresolvedOrgError:
      "Everything else was applied. The organization could not be linked because no single matching organization was found; link it by hand.",
    staleError: "This record changed while you were reviewing. Refresh and try again.",
    mappingsChangedError:
      "An admin changed which fields enrichment writes to. Refresh and review again.",
    runError: "Could not reach the providers. Try again.",
    allFailedError: ALL_FAILED,
    allFailedErrorReasons: (reasons: string) => `${ALL_FAILED} ${reasons}`,
    reasonSeparator: " · ",
    noIdentifierError:
      "This record has nothing to look up by. Add an email, a domain, or a linked organization first.",
    throttledError: (until: string) => `Every provider is rate limited. They resume at ${until}.`,
    throttledErrorUnknown: "Every provider is rate limited. Try again later.",
    unsupportedError:
      "No connected provider can search by what this record holds. Add an email, a domain, or the name of the organization it belongs to.",
    notEntitledError:
      "No connected provider's plan includes this kind of lookup. Upgrade the plan on the provider's side, or connect another provider.",
    keyUnreadableError:
      "A stored API key could not be read. An admin needs to enter it again in Settings.",
    outcomeLine: (provider: string, verdict: string) => `${provider} ${verdict}`,
    outcomeLineUntil: (provider: string, verdict: string, until: string) =>
      `${provider} ${verdict} until ${until}`,
    ageJustNow: "just now",
    ageMinutes: (n: number) => (n === 1 ? "1 minute ago" : `${n} minutes ago`),
    ageHours: (n: number) => (n === 1 ? "1 hour ago" : `${n} hours ago`),
    ageDays: (n: number) => (n === 1 ? "1 day ago" : `${n} days ago`),
  },
  button: {
    label: "Fill the gaps",
    noIdentifier: "Add an email or link an organization first",
    notConfigured: "No enrichment provider is connected",
  },
  outcome: {
    ok: "ok",
    no_match: "no match",
    auth: "key rejected",
    throttled: "rate limited",
    quota: "out of credits",
    timeout: "timed out",
    provider_error: "unavailable",
    skipped: "skipped",
    unsupported: "no usable identifier",
    key_unreadable: "key could not be read",
    not_entitled: "not included in this plan",
  },
} as const;
