// Copy for the CSV import wizard (settings section 10). Extracted from strings.ts
// to keep that file under the 300-line hard cap; referenced as STRINGS.settings.importer.
export const IMPORTER_STRINGS = {
  title: "Import data",
  subtitle: "Import people, organizations, deals, leads, or activities from a CSV file.",
  stepUpload: "Upload",
  stepMap: "Map columns",
  stepPreview: "Preview",
  stepCommit: "Import",
  chooseFile: "CSV file",
  dropzoneTitle: "Drag and drop your CSV here, or click to browse",
  dropzoneHint: "CSV files up to 25 MB",
  fileTooLarge: "That file is too large. Please upload a CSV under 25 MB.",
  entity: "Import as",
  person: "People",
  organization: "Organizations",
  deal: "Deals",
  lead: "Leads",
  activity: "Activities",
  rowsDetected: (n: number) => `${n} rows detected`,
  continue: "Continue",
  dedup: "When a matching contact already exists",
  dedupSkip: "Skip the row",
  dedupUpdate: "Update the existing contact",
  column: "CSV column",
  mapTo: "Maps to",
  unmapped: "Do not import",
  customGroup: "Custom fields",
  nameRequired: "Map a column to Name to continue.",
  rowNote: "Add unmapped columns as a note",
  rowNoteHint: "Columns you do not map are discarded. Keep them as a note on each record.",
  valid: (n: number) => `${n} valid`,
  withErrors: (n: number) => `${n} with errors`,
  rowErrors: "Rows with errors",
  commitButton: (n: number) => `Import ${n} valid rows`,
  importing: "Importing...",
  result: (imported: number, skipped: number, invalid: number) =>
    `${imported} imported, ${skipped} skipped, ${invalid} failed`,
  statusCompleted: "Import complete",
  statusPartial: "Import partially complete",
  statusFailed: "Import failed",
  errorGeneric: "Something went wrong. Please try again.",
  requiresImport: "You do not have permission to import data.",
  importLeads: "Import leads",
  startOver: "Import another file",
  newImport: "New import",
  historyEmpty: "No imports yet.",
  colFile: "File",
  colTarget: "Type",
  colWhen: "When",
  colStatus: "Status",
  colResult: "Result",
  colActions: "",
  downloadErrors: "Download errors",
  undo: "Undo",
  undoing: "Undoing...",
  undone: "Undone",
  resultCounts: (imported: number, errors: number) => `${imported} imported, ${errors} errors`,
} as const;
