import { IMPORTER_STRINGS } from "./importerStrings";

export const SETTINGS_STRINGS = {
  permissionSets: "Permission sets",
  permissionSetsDescription: "Define reusable permission sets for roles and teams.",
  visibilityGroups: "Visibility groups",
  visibilityGroupsDescription: "Control which records groups can see across the workspace.",
  teams: "Teams",
  teamsDescription: "Organize users into teams and assign managers.",
  users: "Users",
  usersDescription: "Invite users, review access, and keep active seats current.",
  notifications: "Notifications",
  notificationsDescription: "Choose which activity updates appear in app or by email.",
  requiresAdmin: "This action requires an administrator.",
  requiresAuth: "Please sign in to view this page.",
  profile: "Personal preferences",
  profileDescription: "Update your account details, photo, timezone, and interface preferences.",
  name: "Name",
  email: "Email",
  timezone: "Timezone",
  timezoneNone: "Use browser default",
  density: "Interface density",
  comfortable: "Comfortable",
  compact: "Compact",
  scheduleFollowUpAfterWon: "Schedule a follow-up activity after marking a deal Won",
  interfaceHeading: "Interface",
  interface: {
    openDetailsAfterCreate: "Open details view after creating a new item",
    openDetailsLeadDeal: "Lead/deal",
    openDetailsPerson: "Person",
    openDetailsOrg: "Organization",
    usPhoneFormat: "Convert phone numbers to US phone number format",
    winSound: "Play a coins sound after every won deal",
    emailLinksNewTab: "Open email links in a new tab",
    prefillParticipantsAsRecipients: "Prefill all deal participants as email recipients",
    autoPrefixLeadDealTitles: 'Automatically add "lead" and "deal" to lead/deal titles',
  },
  save: "Save",
  saved: "Saved",
  saveName: "Save name",
  photo: "Photo",
  uploadPhoto: "Upload photo",
  changePhoto: "Change photo",
  removePhoto: "Remove",
  photoHint: "PNG, JPEG, WebP or GIF, up to 2 MB.",
  photoInvalidType: "Please choose a PNG, JPEG, WebP or GIF image.",
  photoTooLarge: "That image is too large (max 2 MB).",
  photoFailed: "Could not update your photo. Please try again.",
  myAccount: "My account",
  companyOverview: "Company overview",
  companySettings: "Company settings",
  companySettingsDescription:
    "Manage workspace defaults, activity catalogs, lost reasons, and labels.",
  emailSync: "Email sync",
  dataFields: "Data fields",
  emailTemplates: "Email templates",
  signatures: "Signatures",
  importData: "Import data",
  companyGeneral: "General",
  companyName: "Company name",
  baseCurrency: "Base currency",
  activities: "Activities",
  lostReasons: "Lost reasons",
  labels: "Labels",
  pipelines: "Pipelines",
  pipelinesDescription: "Create pipelines and manage their stages.",
  createPipeline: "Create pipeline",
  pipelineNameLabel: "Pipeline name",
  pipelineNamePlaceholder: "e.g. Sales Pipeline",
  createPipelineDescription: "New pipelines start with a default set of stages you can edit.",
  createPipelineError: "Couldn't create the pipeline. Please try again.",
  noPipelinesYet: "No pipelines yet.",
  editStages: "Edit stages",
  creating: "Creating...",
  createFirstPipeline: "Create your first pipeline",
  add: "Add",
  cancel: "Cancel",
  rename: "Rename",
  delete: "Delete",
  archive: "Archive",
  moveUp: "Move up",
  moveDown: "Move down",
  enable: "Enable",
  disable: "Disable",
  enabled: "Enabled",
  disabled: "Disabled",
  systemBadge: "System",
  emptyList: "Nothing here yet.",
  addActivityType: "Add activity type",
  activityTypeName: "Activity type name",
  iconLabel: "Icon",
  deleteTypeBlocked: "Can't delete: this activity type is a system type or is in use.",
  addLostReason: "Add lost reason",
  lostReasonName: "Lost reason",
  addLabel: "Add label",
  labelName: "Label name",
  color: "Color",
  deleteLabelBlocked: "Can't delete: this label is applied to one or more records.",
  targetDeal: "Deals",
  targetPerson: "People",
  targetOrganization: "Organizations",
  targetLead: "Leads",
  entity: "Entity",
  fieldName: "Field name",
  fieldType: "Type",
  fieldOptions: "Options",
  fieldOptionsHelp: "Comma-separated option labels",
  addField: "Add field",
  fieldOptionsRequired: "Add at least one option for an option-type field.",
  addFieldFailed: "Could not add the field. Please try again.",
  noFields: "No custom fields yet.",
  builtinFields: "Built-in fields",
  builtinBadge: "Built-in",
  builtinAlwaysShown: "Always shown",
  builtinHidden: "Hidden",
  builtinHideNote:
    "Hiding a built-in field removes it from add forms, record detail, and the import mapping. Its data is kept and reappears when you unhide it.",
  builtinHideFailed: "Could not update the field. Please try again.",
  entityDeal: "Deal",
  entityPerson: "Person",
  entityOrganization: "Organization",
  entityActivity: "Activity",
  dragHandle: "Drag to reorder",
  important: "Important",
  showInAddForm: "Show in add form",
  editOptions: "Edit options",
  optionLabel: "Option label",
  removeOption: "Remove",
  newOption: "New option",
  addOption: "Add option",
  optionArchived: "Archived",
  columns: {
    name: "Name",
    email: "Email",
    role: "Role",
    active: "Active",
    flagsEnabled: "Flags enabled",
    default: "Default",
    created: "Created",
    manager: "Manager",
  },
  values: {
    admin: "Admin",
    regular: "Regular",
    yes: "Yes",
    no: "No",
    none: "None",
  },
  importer: IMPORTER_STRINGS,
} as const;
