// Centralized UI copy (ops spec E7: English-only v1, but no hardcoded text in components,
// so a future locale layer is a drop-in). No em dashes anywhere.
import { DEAL_SIDEBAR_STRINGS } from "./dealSidebarStrings";
import { ENRICHMENT_STRINGS } from "./enrichmentStrings";
import { INBOX_STRINGS } from "./inboxStrings";
import { SETTINGS_STRINGS } from "./settingsStrings";

export const STRINGS = {
  app: { name: "Warpdrive" },
  nav: {
    pipeline: "Pipeline",
    leads: "Leads",
    deals: "Deals",
    contacts: "Contacts",
    people: "People",
    orgs: "Organizations",
    contactsTimeline: "Timeline",
    activities: "Activities",
    inbox: "Inbox",
    dashboard: "Performance",
    settings: "Settings",
  },
  auth: {
    signInWithGoogle: "Sign in with Google",
    loginTitle: "Sign in to Warpdrive",
    domainOnly: "Use your company Google Workspace account.",
  },
  contacts: {
    peopleHeading: "People",
    colName: "Name",
    colOrg: "Organization",
    colEmail: "Email",
    colPhone: "Phone",
    colClosedDeals: "Closed deals",
    empty: "No people are visible to you yet.",
    orgsHeading: "Organizations",
    orgsEmpty: "No organizations are visible to you yet.",
    colAddress: "Address",
    colPeopleCount: "People",
    colDealCount: "Deals",
    colOpenDeals: "Open deals",
    countLabel: (shown: number, total: number) => `Showing ${shown} of ${total}`,
    addPerson: "+ Person",
    addOrg: "+ Organization",
    nameLabel: "Name",
    add: "Add",
    cancel: "Cancel",
    timelineHeading: "Contacts timeline",
    timelineEmpty: "No recent contact activity.",
  },
  leads: {
    contactPerson: "Contact person",
    searchAddPerson: "Search or add a person",
    addAsNewPerson: (q: string) => `Add '${q}' as new person`,
    similarContact: "Similar contact already exists.",
    organization: "Organization",
    searchAddOrg: "Search or add an organization",
    addAsNewOrg: (q: string) => `Add '${q}' as new organization`,
    similarOrg: "Similar organization already exists.",
    titleLabel: "Title",
    leadTitle: "Lead title",
    valueLabel: "Value",
    leadValue: "Lead value",
    valuePlaceholder: "0",
    labelsLabel: "Labels",
    ownerLabel: "Owner",
    ownerMe: "Me",
    expectedCloseDate: "Expected close date",
    sourceChannel: "Source channel",
    noSourceChannel: "No source channel",
    sourceChannelId: "Source channel ID",
    sourceChannelIdPlaceholder: "Reference / campaign id",
    visibleTo: "Visible to",
    visibleToDefault: "Default",
    emptyTitle: "No leads yet",
    emptyBody:
      "A lead is an unqualified opportunity you work before it earns a place in the pipeline.",
    emptyAction: "Add lead",
    emptyArchivedTitle: "Nothing in the archive",
    emptyArchivedBody:
      "Archiving a lead takes it out of the inbox without deleting it. Nothing is archived right now.",
    emptyArchivedAction: "Back to inbox",
    emptyFilteredTitle: "No leads match these filters",
    // Every count the inbox has is already narrowed by the filter, so this sentence cannot claim
    // leads exist behind it. It has to be true of an empty inbox too.
    emptyFilteredBody:
      "The filters above are the only thing narrowing this view. Clear them to see it whole.",
    emptyFilteredAction: "Clear filters",
  },
  reconnect: { reconnecting: "Reconnecting..." },
  dealSidebar: DEAL_SIDEBAR_STRINGS,
  enrichment: ENRICHMENT_STRINGS,
  inbox: INBOX_STRINGS,
  notifications: {
    title: "Notifications",
    markAllRead: "Mark all read",
    seeAll: "See all activity",
    today: "Today",
    earlier: "Earlier",
    empty: "No notifications yet.",
    labels: {
      mention: "You were mentioned",
      activity_assigned: "Activity assigned",
      activity_reminder: "Reminder",
      deal_followed_update: "Update",
      deal_followed_update_fallback: "a followed deal changed",
      email_open: "Your email was opened",
      email_click: "A link in your email was clicked",
      deal_won: "A deal you follow was won",
      deal_lost: "A deal you follow was lost",
      comment_reply: "New reply to a comment",
      deal_email_received: "New email",
      deal_email_received_fallback: "on a deal",
      fallback: "Notification",
    },
    preferences: {
      pageTitle: "Notification preferences",
      loading: "Loading preferences...",
      columnInApp: "In-app",
      columnEmail: "Email",
      saveError: "Failed to save preference. Please try again.",
      typeLabels: {
        mention: "Mentions",
        activity_assigned: "Activity assigned to me",
        activity_reminder: "Activity reminders",
        deal_followed_update: "Followed-deal updates",
        email_open: "Email opened",
        email_click: "Email link clicked",
        deal_won: "Deal won",
        deal_lost: "Deal lost",
        comment_reply: "Comment replies",
        deal_email_received: "New email on my deals",
      },
    },
  },
  dashboard: {
    title: "Performance",
    ownerToggleLabel: "Owner:",
    ownerMe: "Me",
    ownerAll: "All",
    ownerToggleTitle: "Toggle owner scope",
    ownerToggleDisabledTitle: "You can only view your own stats",
    loading: "Loading...",
    statsUnavailable: "Stats unavailable.",
    widgetDealPerformance: "DEAL PERFORMANCE",
    widgetFunnelConversion: "FUNNEL CONVERSION",
    widgetActivities: "ACTIVITIES PERFORMANCE",
    widgetStageSums: "PER-STAGE VALUE SUMS",
    added: "Added",
    won: "Won",
    lost: "Lost",
    open: "Open now",
    completed: "Completed",
    scheduled: "Scheduled",
    undated: "No due date",
    rangeStartLabel: "Range start",
    rangeEndLabel: "Range end",
    rangeSeparator: "to",
    pipelineLabel: "Pipeline",
    allPipelines: "All pipelines",
    widgetScoreboard: "SCOREBOARD",
    widgetActivityTypes: "ACTIVITIES BY TYPE",
    widgetLostReasons: "WHY DEALS WERE LOST",
    widgetGoals: "GOALS",
    scoreWon: "Deals won",
    scoreWinRate: "Win rate",
    scoreAvgDeal: "Average won deal",
    scoreCycle: "Median sales cycle",
    scoreActivities: "Activities completed",
    days: "days",
    noValue: "-",
    // A duration that rounds to zero days is shorter than the unit reported here, not instant.
    underADay: "Under a day",
    emptyGoalsBody: "A goal sets a target for a person or the team over a period you choose.",
    emptyFunnel: "No deals were created in this range, so there is no funnel to measure.",
    emptyStageSums: "No open deals in these stages.",
    emptyActivityTypes: "No activity types are configured.",
    emptyLostReasons: "No deals were lost in this range.",
    emptyGoals: "No goals apply to you yet.",
    goalsSettingsLink: "Set up goals",
    lostReasonUnspecified: "No reason recorded",
    goalPeriod: "Period",
    goalTarget: "Target",
    goalPace: "Pace",
    goalNotStarted: "Outside this goal's dates",
    goalBooked: "Booked",
    goalTargetPace: "On target",
    widgetWonTrend: "WON DEALS BY MONTH",
    emptyWonTrend: "No deals were won in this range, so there is no trend to draw.",
    trendTableCaption: "Won deals by month",
    trendMonth: "Month",
    trendCount: "Deals won",
    trendValue: "Value won",
    // The funnel is a cohort measure and the board is a live snapshot, so the two disagree by
    // design. The widget has to say which cohort it counted or the gap reads as a bug.
    funnelBasisMe: "Counts only deals you own that were created in this range.",
    funnelBasisAll: "Counts deals created in this range, whoever owns them.",
  },
  search: {
    placeholder: "Search deals, people, organizations, leads...",
    idle: "Type to search",
    resultsLabel: "Search results",
    headingDeals: "Deals",
    headingPeople: "People",
    headingOrganizations: "Organizations",
    headingLeads: "Leads",
    emptyDeals: "No deals",
    emptyPeople: "No people",
    emptyOrganizations: "No organizations",
    emptyLeads: "No leads",
  },
  // Copy for the route error / not-found boundaries. Deliberately vague about the cause: in
  // production Next redacts the message, and the digest is the operator's only handle to the log.
  errors: {
    notFound: "Not found",
    forbidden: "You do not have permission to do that.",
    boundaryTitle: "Something went wrong",
    boundaryBody:
      "This page hit an unexpected error. Trying again may work; if it keeps happening, quote the reference below.",
    referenceLabel: "Reference:",
    retry: "Try again",
    appCrashTitle: "Warpdrive could not start",
    appCrashBody: "Reload the page. If it keeps happening, check the server logs.",
    reload: "Reload",
    notFoundBody: "That record does not exist, or you do not have access to it.",
    backToPipeline: "Back to pipeline",
  },
  board: {
    sort: {
      label: "Sort by",
      ascending: "Sort ascending",
      descending: "Sort descending",
      options: {
        nextActivity: "Next activity",
        title: "Deal title",
        value: "Deal value",
        person: "Linked person",
        organization: "Linked organization",
        updateTime: "Deal update time",
        owner: "Owner name",
      },
    },
    // Screen-reader announcements for board drags (aria-live).
    announcements: {
      pickedUp: (title: string, stage: string): string =>
        `Picked up ${title}${stage !== "" ? `, ${stage}` : ""}`,
      notOverColumn: "Not over a column",
      movedTo: (stage: string): string => `Moved to ${stage}`,
      droppedIn: (stage: string): string => `Dropped in ${stage}`,
      cancelled: "Cancelled",
    },
  },
  customFields: {
    restrictedRef: "Restricted",
  },
  dealsList: {
    emptyTitle: "No deals in this pipeline yet",
    emptyBody:
      "A deal is one opportunity: a value, a stage and an owner. The first one you add shows up here and on the board.",
    emptyArchivedTitle: "Nothing archived",
    emptyArchivedBody:
      "Archiving a deal takes it off the board without deleting it. Anything you archive lands here, ready to restore.",
    emptyArchivedAction: "Back to the board",
    emptyFilteredTitle: "No deals match this filter",
    emptyFilteredBody: "The pipeline still holds deals. The filters above exclude all of them.",
    emptyFilteredAction: "Clear filters",
  },
  calendar: {
    emptyTitle: (view: string) => `Nothing scheduled this ${view}`,
    emptyBody:
      "Only activities due in this window appear here. Step to another week or month to see the rest.",
    emptyAction: "Add activity",
    emptyFilteredTitle: (view: string) => `No activities match these filters this ${view}`,
    emptyFilteredBody: "This window does have activities. The filters above exclude all of them.",
    emptyFilteredAction: "Clear filters",
  },
  titles: {
    calendar: "Calendar",
    dealList: "Deals list",
    editPipeline: "Edit pipeline",
    // Fallbacks when a detail entity has no name yet or is not visible. The pipeline board's
    // fallback reuses nav.pipeline (same word, one source).
    dealFallback: "Deal",
    leadFallback: "Lead",
    personFallback: "Person",
    orgFallback: "Organization",
  },
  settings: SETTINGS_STRINGS,
} as const;
