// Shared DealWorkspace fixture for DealWorkspaceClient tests. Extracted so the test file stays
// under the file-size limit; the shape mirrors what summaryRepo.loadDealWorkspace returns.
export const workspace = {
  ownerName: "A.K.",
  pipelineName: "Sales pipeline",
  owner: { id: "u1", name: "A.K.", avatarUrl: null },
  followers: [],
  isFollowedBySelf: false,
  lostReasonOptions: [],
  deal: {
    id: "d1",
    title: "Acme renewal",
    value: "25000.00",
    labels: [],
    sourceChannel: null,
    expectedCloseDate: null,
    status: "open",
    stageEnteredAt: new Date("2026-06-24T00:00:00Z"),
    stageId: "s2",
    pipelineId: "p1",
    customFields: {},
    personId: "pe1",
    orgId: "o1",
    lostReasonId: null,
    boardPosition: "1",
    ownerId: "u1",
    visibilityLevel: "owner" as const,
    visibilityGroupId: null,
    visibleToUserIds: [],
    deletedAt: null,
    createdAt: new Date("2026-06-24T00:00:00Z"),
    updatedAt: new Date("2026-06-24T00:00:00Z"),
  },
  person: {
    id: "pe1",
    name: "Jane Roe",
    primaryEmail: "jane@acme.com",
    ownerId: "u1",
    orgId: "o1",
    // Required by PersonBlock (deal-sidebar-parity, merged after this fixture was written):
    // it maps over person.phones/emails unconditionally, so an absent array crashes the render.
    phones: [],
    emails: [],
    visibilityLevel: "owner" as const,
    visibilityGroupId: null,
    visibleToUserIds: [],
    customFields: {},
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  org: {
    id: "o1",
    name: "Acme Inc",
    ownerId: "u1",
    // Required by OrgBlock (deal-sidebar-parity, merged after this fixture was written): it
    // reads org.address unconditionally (null is handled, undefined is not) plus the other
    // firmographics fields, which are all optional-chained except address.
    address: null,
    domain: null,
    industry: null,
    employeeCount: null,
    annualRevenue: null,
    linkedinUrl: null,
    visibilityLevel: "owner" as const,
    visibilityGroupId: null,
    visibleToUserIds: [],
    customFields: {},
    deletedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  stageProgress: {
    chips: [
      { id: "s1", name: "Qualified", current: false, passed: true, days: 0 },
      { id: "s2", name: "Proposal", current: true, passed: false, days: 6 },
    ],
    daysInStage: 6,
    rotting: false,
  },
  followerIds: [],
  lostReasonName: null,
  customFieldDefs: [],
};
